DROP DATABASE IF EXISTS library;

CREATE DATABASE IF NOT EXISTS library DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;

USE library;

CREATE TABLE IF NOT EXISTS members (
    id INT UNSIGNED AUTO_INCREMENT NOT NULL PRIMARY KEY,
    first_name VARCHAR(30) NOT NULL,
    last_name VARCHAR(30) NOT NULL,
    member_address VARCHAR(100) NOT NULL,
    city VARCHAR(50) NOT NULL,
    email VARCHAR(100) NOT NULL,
    membership_id CHAR(14) NOT NULL UNIQUE
)ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS ganre (
    id INT UNSIGNED AUTO_INCREMENT NOT NULL PRIMARY KEY,
    ganre_type VARCHAR(40) NOT NULL
)ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS books (
    id INT UNSIGNED AUTO_INCREMENT NOT NULL PRIMARY KEY,
    title VARCHAR(100) NOT NULL,
    author VARCHAR(100) NOT NULL,
    publisher VARCHAR(100) NOT NULL,
    publication_year CHAR(4) NOT NULL,
    isbn INT(12) NOT NULL,
    ganre_id INT UNSIGNED NOT NULL,
    FOREIGN KEY (ganre_id) REFERENCES ganre(id)
)ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS book_copy (
    id INT UNSIGNED AUTO_INCREMENT NOT NULL PRIMARY KEY,
    book_id INT UNSIGNED NOT NULL,
    FOREIGN KEY (book_id) REFERENCES books(id)
)ENGINE=InnoDB;


CREATE TABLE IF NOT EXISTS late_fee (
    id INT UNSIGNED AUTO_INCREMENT NOT NULL PRIMARY KEY,
    fee INT UNSIGNED,
    book_id INT UNSIGNED NOT NULL,
    FOREIGN KEY (book_id) REFERENCES books(id)
)ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS borrow (
    id INT UNSIGNED AUTO_INCREMENT NOT NULL PRIMARY KEY,
    borrow_date DATE NOT NULL,
    return_date DATE NOT NULL,
    late_fee INT UNSIGNED NOT NULL,
    FOREIGN KEY (late_fee) REFERENCES late_fee(id),
    member_id INT UNSIGNED NOT NULL,
    FOREIGN KEY (member_id) REFERENCES members(id),
    book_id INT UNSIGNED NOT NULL,
    FOREIGN KEY (book_id) REFERENCES books(id)
)ENGINE=InnoDB;