DROP DATABASE IF EXISTS videoteka;

CREATE DATABASE IF NOT EXISTS videoteka DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;

USE videoteka;


CREATE TABLE IF NOT EXISTS price (
    id INT UNSIGNED AUTO_INCREMENT NOT NULL PRIMARY KEY,
    movie_age_type VARCHAR(60) NOT NULL,
    price INT NOT NULL
)ENGINE=InnoDB;


CREATE TABLE IF NOT EXISTS members (
    id INT UNSIGNED AUTO_INCREMENT NOT NULL PRIMARY KEY,
    member_name VARCHAR(50) NOT NULL,
    member_address VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL
)ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS movies (
    id INT UNSIGNED AUTO_INCREMENT NOT NULL PRIMARY KEY,
    title VARCHAR(100) NOT NULL,
    genre VARCHAR(10) NOT NULL,
    movie_age_type VARCHAR(255) NOT NULL,
    format VARCHAR(10) NOT NULL,
    price_id INT UNSIGNED NOT NULL,
    FOREIGN KEY (price_id) REFERENCES price(id)
)ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS rental (
    id INT UNSIGNED AUTO_INCREMENT NOT NULL PRIMARY KEY,
    rental_date TIMESTAMP NOT NULL,
    return_date TIMESTAMP NOT NULL,
    penalty VARCHAR(255) NOT NULL,
    membership_id INT UNSIGNED NOT NULL,
    FOREIGN KEY (membership_id) REFERENCES members(id),
    movie_id INT UNSIGNED NOT NULL,
    FOREIGN KEY (movie_id) REFERENCES movies(id)
)ENGINE=InnoDB;


